services:
  - type: web
    name: smash-elo-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ADMIN_USER_1
        sync: false
      - key: ADMIN_USER_2
        sync: false
      - key: ADMIN_USER_3
        sync: false
      - key: ADMIN_NAMES
        sync: false
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
